// <auto-generated />
using System;
using FlightAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightAPI.Migrations
{
    [DbContext(typeof(FlightDBContext))]
    [Migration("20201003182235_Initial Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlightAPI.Models.Flight", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("delay")
                        .HasColumnType("int");

                    b.Property<string>("flightName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("fromCity")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("fromTimeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("toCity")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("toTimeDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
